/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/AppNavigator` | `/AppNavigator`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/carwash` | `/carwash`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/firebaseConfig` | `/firebaseConfig`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/notifications` | `/notifications`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/SignInScreen` | `/SignInScreen`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/SignUpScreen` | `/SignUpScreen`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/transport` | `/transport`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/utilities` | `/utilities`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/AppNavigator` | `/AppNavigator`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/carwash` | `/carwash`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/firebaseConfig` | `/firebaseConfig`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/notifications` | `/notifications`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/SignInScreen` | `/SignInScreen`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/SignUpScreen` | `/SignUpScreen`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/transport` | `/transport`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/utilities` | `/utilities`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } };
      href: Router.RelativePathString | Router.ExternalPathString | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/AppNavigator${`?${string}` | `#${string}` | ''}` | `/AppNavigator${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/carwash${`?${string}` | `#${string}` | ''}` | `/carwash${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/firebaseConfig${`?${string}` | `#${string}` | ''}` | `/firebaseConfig${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/notifications${`?${string}` | `#${string}` | ''}` | `/notifications${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/profile${`?${string}` | `#${string}` | ''}` | `/profile${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/SignInScreen${`?${string}` | `#${string}` | ''}` | `/SignInScreen${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/SignUpScreen${`?${string}` | `#${string}` | ''}` | `/SignUpScreen${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/transport${`?${string}` | `#${string}` | ''}` | `/transport${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/utilities${`?${string}` | `#${string}` | ''}` | `/utilities${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/AppNavigator` | `/AppNavigator`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/carwash` | `/carwash`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/firebaseConfig` | `/firebaseConfig`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/notifications` | `/notifications`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/SignInScreen` | `/SignInScreen`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/SignUpScreen` | `/SignUpScreen`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/transport` | `/transport`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/utilities` | `/utilities`; params?: Router.UnknownInputParams; } | `/+not-found` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
    }
  }
}
